### ISSUE TITLE
Exception in thread "main" java.lang.IllegalArgumentException: Expected string, integral, double or boolean data type, got vector data type

### ISSUE THREAD

**Issue by sunyichao** [jpmml/jpmml-sparkml#79] opened 2019-09-18 14:30 UTC
how to solve it

**Comment by vruusmann** [comment] 2019-09-18 20:31
Exact duplicate of https://github.com/jpmml/jpmml-sparkml/issues/26

**Closed by vruusmann** 2019-09-18 20:31 UTC
