### ISSUE TITLE
Support for HashingTFModel

### ISSUE THREAD

**Issue by avisheknag17** [jpmml/jpmml-sparkml#74] opened 2019-08-14 11:55 UTC
Hi,

I didn't find support for HashingTF. I need to do TF-IDF transformation for text
I am getting this exception:

Traceback (most recent call last):
  File "/opt/spark-2.2.1-master/bin/enclosures_pyspark_model.py", line 125, in <module>
    build_and_train_model()
  File "/opt/spark-2.2.1-master/bin/enclosures_pyspark_model.py", line 121, in build_and_train_model
    pmmlBuilder.buildFile("enclosures_pyspark_model.pmml")
  File "/Users/avnag/Library/Python/2.7/lib/python/site-packages/pyspark2pmml/__init__.py", line 27, in buildFile
    javaFile = self.javaPmmlBuilder.buildFile(javaFile)
  File "/opt/spark-2.2.1-master/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
  File "/opt/spark-2.2.1-master/python/lib/pyspark.zip/pyspark/sql/utils.py", line 79, in deco
pyspark.sql.utils.IllegalArgumentException: u'Transformer class org.apache.spark.ml.feature.HashingTF is not supported'

**Comment by vruusmann** [comment] 2019-08-14 18:27
Duplicate of #20

**Closed by vruusmann** 2019-08-14 18:27 UTC
