### ISSUE TITLE
生成分类XGB模型的时候，pmml文件中 OutputField属性出现重复，再加载模型文件的时候报错。<OutputField name="probability(0)" optype="continuous" dataType="double" feature="probability" value="0"/> <OutputField name="probability(1)" optype="continuous" dataType="double" feature="probability" value="1"/> <OutputField name="probability(0)" optype="continuous" dataType="double" feature="probability" value="0"/> <OutputField name="probability(1)" optype="continuous" dataType="double" feature="probability" value="1"/>

### ISSUE THREAD

**Issue by ScavengerDD** [jpmml/jpmml-sparkml#92] opened 2020-04-01 03:41 UTC
<OutputField name="probability(0)" optype="continuous" dataType="double" feature="probability" value="0"/>
<OutputField name="probability(1)" optype="continuous" dataType="double" feature="probability" value="1"/>
<OutputField name="probability(0)" optype="continuous" dataType="double" feature="probability" value="0"/>
<OutputField name="probability(1)" optype="continuous" dataType="double" feature="probability" value="1"/>

**Comment by ScavengerDD** [comment] 2020-04-01 03:43
org.jpmml.evaluator.InvalidElementException (at or around line 9860 of the PMML document): Element OutputField is not valid

**Comment by vruusmann** [comment] 2020-04-01 05:06
There are duplicate `OutputField` elements with name `probability(0)` and `probability(1)`.

This looks like a duplicate of https://github.com/jpmml/jpmml-sparkml-xgboost/issues/13

Please upgrade all JPMML conversion libraries to their latest versions.

**Closed by vruusmann** 2020-04-01 05:06 UTC
