### ISSUE TITLE
feature datatype not support array?

### ISSUE THREAD

**Issue by marvinxu-free** [jpmml/jpmml-sparkml#88] opened 2020-01-09 06:23 UTC
when i use use pmml, i found that model load from pmml not support array type,

**Comment by vruusmann** [comment] 2020-01-09 09:02
Exact duplicate of https://github.com/jpmml/pyspark2pmml/issues/26

The "expected scalar type, got array type" error is conceptually very close to the "expected scalar type, got vector type" error, which is documented in https://github.com/jpmml/jpmml-sparkml/issues/21, https://github.com/jpmml/jpmml-sparkml/issues/26 etc.

The resolution is still the same - you cannot use structured column types (such as maps, vectors etc) in your data frame. They need to be unpacked (aka flattened, exploded etc) to plain scalar column types. See the instructions in the linked issues.

> when i use CountVectorizer in my pipeline model, which can not save as a jpmml model

The `CountVectorizer` transformation type is supported, but you need to apply to to a string column, not map/vector/array column.

**Closed by vruusmann** 2020-01-09 09:02 UTC

**Comment by marvinxu-free** [comment] 2020-01-09 22:31
use string indexer and one-hot stage will lead to spark program run very slow and even failed, while CountVectorizer with VectorAssembler is fastest  and  can not save with jpmml; 

mleap  support array type column, which means this is not an unresolvable problem, but the predict result is not same while load save model in local environment for mleap, maybe i miss something...

**Comment by marvinxu-free** [comment] 2020-01-12 08:25
> use string indexer and one-hot stage will lead to spark program run very slow and even failed, while CountVectorizer with VectorAssembler is fastest and can not save with jpmml;
> 
> mleap support array type column, which means this is not an unresolvable problem, but the predict result is not same while load save model in local environment for mleap, maybe i miss something...

mleap has a bug,  do not use min_max scaler can resolve this problem , thus I suggest any one see this problem to using mleap in your service.
