### ISSUE TITLE
Spark pipeline was not converted properly

### ISSUE THREAD

**Issue by LittileFatNoRun** [jpmml/jpmml-sparkml#32] opened 2017-11-21 05:13 UTC
I am writing a scala project using spark pipeline with GBDT model and stringIndexer to convert NominalColumns. And I convert the pipeline model to PMML. But when i using PMML model to predict there is a input data mismatch. I think that is because stringIndexer is not converted to PMML. But JPMML support spark stringIndex operation. I don't know why. Exception messages as follow.
```
Caused by: org.jpmml.evaluator.InvalidResultException (at or around line 23)
	at org.jpmml.evaluator.FieldValueUtil.performInvalidValueTreatment(FieldValueUtil.java:178)
	at org.jpmml.evaluator.FieldValueUtil.prepareInputValue(FieldValueUtil.java:90)
	at org.jpmml.evaluator.InputField.prepare(InputField.java:64)
```

**Comment by vruusmann** [comment] 2017-11-21 05:54
This issue is a functional duplicate of https://github.com/jpmml/jpmml-evaluator/issues/84

In brief, your testing data is not "compatible" with the training data - for some categorical feature(s), the testing data contains category values that were not present in training data. The JPMML-Evaluator library then refuses to score such data records, because the prediction would be non-sensical.

**Comment by vruusmann** [comment] 2017-11-21 05:59
Also, what is your Apache Spark ML version, and how is the `StringIndexer` transformation configured?

For example, in Apache Spark ML version 2.2 it is possible to specify how invalid values should be handled by setting the `StringIndexer@handleInvalid` attribute. In this case, the value of this attribute should be set to "keep".

**Comment by LittileFatNoRun** [comment] 2017-11-21 06:21
I am using Spark ML version 2.2.0
This is my StringIndexer configuration.
def getStringIndexer(columnNames:Array[String]):Array[PipelineStage]={
  var stringIndexers : Array[PipelineStage] = new Array[PipelineStage](0)
  for (i <- 0 until  columnNames.length)
  {
    val indexer = new StringIndexer()
      .setInputCol(columnNames(i))
      .setOutputCol(columnNames(i)+"Indexer")
    stringIndexers = stringIndexers:+indexer
  }
  stringIndexers
}

**Comment by vruusmann** [comment] 2017-11-21 06:31
> This is my StringIndexer configuration.

You're using the default `StringIndexer@handleInvalid` attribute value, which is "error". Check Apache Spark ML documentation - it is a scoring error (implemented as `InvalidResultException` in the JPMML-Evaluator library) if the input contains a previously unseen category value.

Please note that the native Apache Spark ML workflow would also fail to make a prediction in this case.

You need to do the following to make unseen categories scorable:
```Scala
val indexer = new StringIndexer()
  .setInputCol(columnNames(i))
  .setOutputCol(columnNames(i) + "Indexer")
  .setHandleInvalid("keep"); // THIS!
```

**Closed by vruusmann** 2017-11-21 06:31 UTC

**Comment by LittileFatNoRun** [comment] 2017-11-21 07:07
Thanks a lot @vruusmann  ! That's really helpful.  ^O^
