### ISSUE TITLE
val pmml_model = new PMMLBuilder(schema,pipeline_model).build() => error skip

### ISSUE THREAD

**Issue by robin-su** [jpmml/jpmml-sparkml#49] opened 2018-08-16 01:16 UTC
When I train the sample, I use StringIndexer to execute the following statement:
Val pmml_model = new PMMLBuilder(schema,pipeline_model).build()

The error is:
```
Exception in thread "main" java.lang.IllegalArgumentException: skip
	at org.jpmml.sparkml.feature.StringIndexerModelConverter.encodeFeatures(StringIndexerModelConverter.java:65)
	at org.jpmml.sparkml.FeatureConverter.registerFeatures(FeatureConverter.java:47)
	at org.jpmml.sparkml.PMMLBuilder.build(PMMLBuilder.java:114)
	at com.nubia.train.Ad_ctr_train$.main(Ad_ctr_train.scala:182)
	at com.nubia.train.Ad_ctr_train.main(Ad_ctr_train.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:745)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by vruusmann** [comment] 2018-08-16 06:37
Exact duplicate of https://github.com/jpmml/jpmml-sparkml/issues/48

Did you read my answer/explanation at all?

**Closed by vruusmann** 2018-08-16 06:37 UTC
